### ISSUE TITLE
Update Compare Meter Threshold with Subtotal:

### ISSUE THREAD

**Issue by Asok17** [addonify/addonify-floating-cart#137]
- [x] Change the label to `Include Discount Amount in Threshold Amount`.
- [x] Change the field to toggle switch. If enabled, include discount amount in threshold amount. Else exclude.

**Comment by h1dd3nsn1p3r** [comment]
Check commits: 

https://github.com/addonify/addonify-floating-cart/commit/548e5ca3f94512f503f7fbd408e36b9f3b3a21b2 & https://github.com/addonify/addonify-floating-cart/commit/fa8004c7ff0646ef6c4c6d3aafe5b8c9d8520845

**Comment by Asok17** [comment]
The issue has been fixed with the commit #143
