### ISSUE TITLE
New: Add option to switch between close and cart button in cart footer

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [addonify/addonify-floating-cart#158]
New: Add an option to switch between the close and cart buttons in the cart footer. 

![image](https://user-images.githubusercontent.com/21140404/235654388-c90658bc-9034-4cc1-9700-d4200e723e62.png)

Ref: https://wordpress.org/support/topic/close-button-43/#post-16703048

**Comment by h1dd3nsn1p3r** [comment]
Added in version 1.1.2

![image](https://user-images.githubusercontent.com/21140404/235854984-587132ed-e87f-432b-8d93-779c21d8a231.png)

**Comment by Asok17** [comment]
Completed. #159
