### ISSUE TITLE
Shopping meter enabled by default

### ISSUE THREAD

**Issue by SharatJaswal** [addonify/addonify-floating-cart#191]
Hi Anuj

I just updated the plugin. It enabled the shopping meter by itself. When i disable it, it wont let me save changes. Says "oops, error saving settings!!"

**Comment by SharatJaswal** [comment]
And we have a horizontal scrollbar on the plugin page for some reason as well. Minor bugs. Thanks!

**Comment by h1dd3nsn1p3r** [comment]
1. Shopping meter, problem acknowledged. For now as a quick fix if you want to hide it, paste the below CSS code at `additional CSS box`

```
#adfy__floating-cart .adfy__woofc-shipping-bar {

    display: none;
}
```

2. Horizontal scrollbar, can I please have a screenshot here?

**Comment by SharatJaswal** [comment]
> 1. Shopping meter, problem acknowledged. For now as a quick fix if you want to hide it, paste the below CSS code at `additional CSS box`
> 
> ```
> #adfy__floating-cart .adfy__woofc-shipping-bar {
> 
>     display: none;
> }
> ```
> 
> 2. Horizontal scrollbar, can I please have a screenshot here?


I have attached the screenshot. I have also cleared the browser cache but have not tried it in a different browser. I use Chrome
![screenshot-nimbusweb me-2023 05 12-09_39_56](https://github.com/addonify/addonify-floating-cart/assets/132910286/e9f59624-0f0a-4703-966c-332ea318bed4)

**Comment by h1dd3nsn1p3r** [comment]
Hi, ignore this scrollbar issue for now as we will implement a new setting page UI shortly. If you wish to try the new setting page UI, you can check the [Addonify Wishlist plugin](https://wordpress.org/plugins/addonify-wishlist/).  

The shopping meter is enabled by default, this issue has been fixed. We will release an update shortly so you can install it. Once you update Addonify Floating Cart to version `1.1.6` please make sure to remove the CSS code that I had given you earlier.

**Comment by Asok17** [comment]
Since the issue had been fixed. I am closing this issue.
