### ISSUE TITLE
unable to Open Cart on Add to Cart Button Click

### ISSUE THREAD

**Issue by deepak2221** [addonify/addonify-floating-cart#202]
unable to Open Cart on Add to Cart Button Click, Open Cart on View Cart Button Click and cant display Toast Notification

**Comment by Asok17** [comment]
Hi @deepak2221,

Could you please share your website's link?

Best regards.

**Comment by deepak2221** [comment]
https://shop.inkholic.in

**Comment by Asok17** [comment]
Cart does not open when product is added to cart from product single page. The cart opens only when product is added into the cart via AJAX on product catalog pages.

The plugin does not support AJAX add to cart for product single page.

**Comment by deepak2221** [comment]
So whats the solution?

**Comment by Asok17** [comment]
Hi @deepak2221 

I am sorry to inform you that there is no solution available for now. But in the future update we may be adding it.

Best regards.
