### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by shajhan** [addonify/addonify-floating-cart#244]
When i disable or delete the plugin it still shows on my website. and when i make changes to the plugin nothing changes. what could be the reason?

**Comment by shajhan** [comment]
also the floating cart button is center of the screen, have no complete control over this as well. 
![image](https://github.com/addonify/addonify-floating-cart/assets/33996747/b50fb80a-b33e-43c8-a0b4-a45e97004b57)

**Comment by h1dd3nsn1p3r** [comment]
Hi @shajhan 

This looks like a cache issue. Please help me with the following answers:

1. Are you using a cache plugin? If yes, which is the plugin?
2. Are you using object cache plugins like Redis or Memcache?
3. On the Floating Cart setting page are you experiencing any issues while saving the changes?

Looking forward.

**Comment by shajhan** [comment]
Hi you were right. i checked my site LiteSpeed Cache and then did this,

![image](https://github.com/addonify/addonify-floating-cart/assets/33996747/4a2d462b-d795-4b04-bccd-ffe71e916eaa)

but only thing is i have to do that all the time after i make a change to the Floating plugin

**Comment by h1dd3nsn1p3r** [comment]
LSCache does quite aggressive caching. Follow this guide: 

1. Go to LSCache > page optimization > JS settings & use this settings.

<img width="880" alt="image" src="https://github.com/addonify/addonify-floating-cart/assets/21140404/f7d7d9bb-b054-401e-80cb-b4c9f1b27e28">

2. Under LSCache > page optimization > Tuning.  

![image](https://github.com/addonify/addonify-floating-cart/assets/21140404/1f2d8a62-8eee-42c2-b1b1-5f90300055f9)

Try excluding the Floating cart JS file. Below is the full URL of the public facing javascript file. 

`https://mydomain.com/wp-content/plugins/addonify-floating-cart/public/assets/build/js/public.min.js`

**Note:** Make sure to change mydomain.com to your actual website address.

Finally, let's exclude the floating cart admin dashboard setting page too.

3. Go to LSCache > Cache > Exclude

![image](https://github.com/addonify/addonify-floating-cart/assets/21140404/8304b040-39ce-477f-aa59-49e69e5c06d8)

Paste the string `page=addonify_floating_cart` in the **do not cache URL's** field then save.

Let's see if this will fix the issue.

**Comment by shajhan** [comment]
Thank you so much!
