### ISSUE TITLE
Add text modification for coupons

### ISSUE THREAD

**Issue by TheRadicalDreamer** [addonify/addonify-floating-cart#272]
I love this plugin, but i am still missing the option to modify the text related to coupons:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/c1a2cc30-596b-4590-bc37-101de5f3b6b7)

In the settings there is no way to change this:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/0559e572-9b42-418a-8ec0-d7735e1892f2)
"have a coupon?"

Nor these:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/db8f52d5-0a98-4f88-b961-cf95bb3b4721)
"Go back"
"please enter a coupon code"
"If you have a coupon code, please apply it below."
"black friday"

Or this:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/eb24a4d5-dec8-4339-be69-14a0af72a038)
"Applied coupon"

Could you please add this text in the settings?

**Comment by TheRadicalDreamer** [comment]
Also
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/2761c788-fe46-4ea9-8eeb-29e905076e93)

"Coupon code removed"

**Comment by TheRadicalDreamer** [comment]
I would also add these texts:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/bb5562de-58dc-48a5-9ec2-477e60743a79)

"item has been removed"
"your cart is currently empty"
"undo?"

**Comment by TheRadicalDreamer** [comment]
And the item counter next to the cart title:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/e5846bd6-469e-4847-b21a-61d2a80e687b)

**Comment by TheRadicalDreamer** [comment]
I have already translated all these strings in the language project, for spanish:
https://translate.wordpress.org/projects/wp-plugins/addonify-floating-cart/stable/es/default/?filters%5Bstatus%5D=waiting

But i really prefer them to be editable within the settings. 😃

**Comment by TheRadicalDreamer** [comment]
@h1dd3nsn1p3r can you help me?

**Comment by h1dd3nsn1p3r** [comment]
Hi @TheRadicalDreamer

We have planned for the custom labels option soon. BUT for now please use [Loco translate](https://wordpress.org/plugins/loco-translate/) plugin to translate the plugin strings.

**Comment by TheRadicalDreamer** [comment]
Thanks.
I''ve tried with Loco, but i don't get it to work.

I have translated other plugins as well, but this does not work for a reason:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/5b3a75a9-6a98-447e-bcfc-4f23e0f38972)

![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/a110a32f-78e0-4deb-8cfc-376b878bae73)

**Comment by h1dd3nsn1p3r** [comment]
I will post the test result as soon as possible! 

**Note:** We will add the option to change the labels from the settings page in the next update. Here's PR https://github.com/addonify/addonify-floating-cart/pull/276

**Comment by h1dd3nsn1p3r** [comment]
Just tested Loco translate plugin. It worked for me when I moved the translation files to `languages/plugins/` DIR. (Screenshot)

![image](https://github.com/addonify/addonify-floating-cart/assets/21140404/f7a352d9-1fc7-4e48-94f5-3a3ec26bec4d)

Do you mind trying?

**Comment by TheRadicalDreamer** [comment]
YES!

that made  the change.

Weird.

I have never had this issue with another translation.

Hope you can submit the entries of the translation project in the next version. :)

**Comment by h1dd3nsn1p3r** [comment]
Hi @TheRadicalDreamer 

Definitely 👍

**Comment by TheRadicalDreamer** [comment]
There is still a couple of labels need to be added!
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/5ec1eb4f-2704-48d5-b8da-719f1676667c)

The Go back
if you have a coupon...


![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/32661010-ca93-4888-8205-2fa3a63e0d84)
Have a coupon?

I can find those strings in the new settings, but they do nothing on the frontend:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/e1aa430a-f268-4ae9-a2fd-95cbe6a27ea1)

![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/e271d1af-706f-4022-a424-bf43fde55936)

**Comment by h1dd3nsn1p3r** [comment]
Added in **v1.2.6**. Closing this issue.
