### ISSUE TITLE
A way to not display shipping costs

### ISSUE THREAD

**Issue by TheRadicalDreamer** [addonify/addonify-floating-cart#273]
There should be an option to not display the shipping costs in the cart.
I prefer users to have the subtotal in the cart, and the in the checkout get the whole info.

**Comment by TheRadicalDreamer** [comment]
These are my Woo settings:
![image](https://github.com/addonify/addonify-floating-cart/assets/11801254/c52bac5d-3a06-4513-84a6-b073e022abfc)

It should be hidden, because of that setting

**Comment by h1dd3nsn1p3r** [comment]
Hi @TheRadicalDreamer we are adding this feature in next update. https://github.com/addonify/addonify-floating-cart/pull/276

**Comment by h1dd3nsn1p3r** [comment]
Added in version **1.2.4**
